"""The owned-audiobooks catalog.

One entry per audiobook (or per volume of a series). The dict shape is
documented in :mod:`audiobooktools.schema`. ``single(...)`` is the convenience
constructor for layout=single entries; layouts other than ``single`` are
written as full dicts.
"""

from __future__ import annotations

from audiobooktools.schema import GENRE, single
from catalog.descriptions import ABERCROMBIE, DESC, LINCOLN_CAST, PACEY

BOOKS: list[dict] = [
    single(
        "Age of Madness Trilogy",
        "Age of Madness - 01 A Little Hatred.m4b",
        title="A Little Hatred",
        subtitle="The Age of Madness, Book One",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="A Little Hatred",
        year="2019",
        series="The Age of Madness",
        series_index="1",
    ),
    single(
        "Age of Madness Trilogy",
        "Age of Madness - 02 The Trouble with Peace.m4b",
        title="The Trouble with Peace",
        subtitle="The Age of Madness, Book Two",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="The Trouble with Peace",
        year="2020",
        series="The Age of Madness",
        series_index="2",
    ),
    single(
        "Age of Madness Trilogy",
        "Age of Madness - 03 The Wisdom of Crowds.m4b",
        title="The Wisdom of Crowds",
        subtitle="The Age of Madness, Book Three",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="The Wisdom of Crowds",
        year="2021",
        series="The Age of Madness",
        series_index="3",
    ),
    single(
        "Andy Weir - Project Hail Mary",
        "Andy Weir - Project Hail Mary.m4b",
        title="Project Hail Mary",
        subtitle="",
        author="Andy Weir",
        narrator="Ray Porter",
        album="Project Hail Mary",
        year="2021",
        series="",
        series_index="",
    ),
    single(
        "Dungeon Crawler Carl",
        "Dungeon Crawler Carl, Book 1.m4b",
        title="Dungeon Crawler Carl",
        subtitle="Dungeon Crawler Carl, Book One",
        author="Matt Dinniman",
        narrator=None,
        album="Dungeon Crawler Carl",
        year="2021",
        series="Dungeon Crawler Carl",
        series_index="1",
    ),
    single(
        "Dungeon Crawler Carl",
        "Carl's Doomsday Scenario Dungeon Crawler Carl, Book 2.m4b",
        title="Carl's Doomsday Scenario",
        subtitle="Dungeon Crawler Carl, Book Two",
        author="Matt Dinniman",
        narrator=None,
        album="Carl's Doomsday Scenario",
        year="2021",
        series="Dungeon Crawler Carl",
        series_index="2",
    ),
    single(
        "Dungeon Crawler Carl",
        "The Dungeon Anarchist's Cookbook Dungeon Crawler Carl, Book 3.m4b",
        title="The Dungeon Anarchist's Cookbook",
        subtitle="Dungeon Crawler Carl, Book Three",
        author="Matt Dinniman",
        narrator=None,
        album="The Dungeon Anarchist's Cookbook",
        year="2021",
        series="Dungeon Crawler Carl",
        series_index="3",
    ),
    single(
        "Dungeon Crawler Carl",
        "The Gate of the Feral Gods, Book 4.m4b",
        title="The Gate of the Feral Gods",
        subtitle="Dungeon Crawler Carl, Book Four",
        author="Matt Dinniman",
        narrator=None,
        album="The Gate of the Feral Gods",
        year="2021",
        series="Dungeon Crawler Carl",
        series_index="4",
        description=DESC["dcc4"],
    ),
    single(
        "Dungeon Crawler Carl",
        "The Butcher's Masquerade, Book 5.m4b",
        title="The Butcher's Masquerade",
        subtitle="Dungeon Crawler Carl, Book Five",
        author="Matt Dinniman",
        narrator=None,
        album="The Butcher's Masquerade",
        year="2022",
        series="Dungeon Crawler Carl",
        series_index="5",
        description=DESC["dcc5"],
    ),
    single(
        "Dungeon Crawler Carl",
        "The Eye of the Bedlam Bride, Book 6.m4b",
        title="The Eye of the Bedlam Bride",
        subtitle="Dungeon Crawler Carl, Book Six",
        author="Matt Dinniman",
        narrator=None,
        album="The Eye of the Bedlam Bride",
        year="2023",
        series="Dungeon Crawler Carl",
        series_index="6",
        description=DESC["dcc6"],
    ),
    single(
        "Dungeon Crawler Carl",
        "This Inevitable Ruin, Book 7.m4b",
        title="This Inevitable Ruin",
        subtitle="Dungeon Crawler Carl, Book Seven",
        author="Matt Dinniman",
        narrator=None,
        album="This Inevitable Ruin",
        year="2025",
        series="Dungeon Crawler Carl",
        series_index="7",
    ),
    single(
        "Dungeon Crawler Carl",
        "A Parade of Horribles, Book 8.m4b",
        title="A Parade of Horribles",
        subtitle="Dungeon Crawler Carl, Book Eight",
        author="Matt Dinniman",
        narrator=None,
        album="A Parade of Horribles",
        year="2026",
        series="Dungeon Crawler Carl",
        series_index="8",
        description=DESC["dcc8"],
    ),
    single(
        "Joe Abercrombie - The Devils",
        "Joe Abercrombie - The Devils.m4b",
        title="The Devils",
        subtitle="The Devils, Book One",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="The Devils",
        year="2025",
        series="The Devils",
        series_index="1",
        description=DESC["the_devils"],
    ),
    single(
        "Neil Gaiman Dirk Maggs - The Sandman",
        "Neil Gaiman Dirk Maggs - The Sandman.m4b",
        title="The Sandman",
        subtitle="Act I",
        author="Neil Gaiman",
        narrator="Full Cast",
        album="The Sandman: Act I",
        year="2020",
        series="The Sandman",
        series_index="1",
    ),
    single(
        "Neil Gaiman Dirk Maggs - The Sandman",
        "Neil Gaiman Dirk Maggs - The Sandman Act II.m4b",
        title="The Sandman",
        subtitle="Act II",
        author="Neil Gaiman",
        narrator="Full Cast",
        album="The Sandman: Act II",
        year="2021",
        series="The Sandman",
        series_index="2",
    ),
    single(
        "Neil Gaiman Dirk Maggs - The Sandman",
        "Neil Gaiman Dirk Maggs - The Sandman Act III.m4b",
        title="The Sandman",
        subtitle="Act III",
        author="Neil Gaiman",
        narrator="Full Cast",
        album="The Sandman: Act III",
        year="2022",
        series="The Sandman",
        series_index="3",
    ),
    single(
        "The Blacktongue Thief",
        "The Blacktongue Thief by Christopher Buehlman.m4b",
        title="The Blacktongue Thief",
        subtitle="",
        author="Christopher Buehlman",
        narrator="Christopher Buehlman",
        album="The Blacktongue Thief",
        year="2021",
        series="Blacktongue",
        series_index="1",
    ),
    single(
        "The First Law Trilogy",
        "Joe Abercrombie - 01 The Blade Itself.m4b",
        title="The Blade Itself",
        subtitle="The First Law, Book One",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="The Blade Itself",
        year="2010",
        series="The First Law",
        series_index="1",
    ),
    single(
        "The First Law Trilogy",
        "Joe Abercrombie - 02 Before They Are Hanged.m4b",
        title="Before They Are Hanged",
        subtitle="The First Law, Book Two",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="Before They Are Hanged",
        year="2010",
        series="The First Law",
        series_index="2",
    ),
    single(
        "The First Law Trilogy",
        "Joe Abercrombie - 03 Last Argument of Kings.m4b",
        title="Last Argument of Kings",
        subtitle="The First Law, Book Three",
        author=ABERCROMBIE,
        narrator=PACEY,
        album="Last Argument of Kings",
        year="2010",
        series="The First Law",
        series_index="3",
    ),
    single(
        "The_Lord_of_the_Rings_J_R_R_Tolkien",
        "The Fellowship of the Ring Lord of the Rings, Book 1.m4b",
        title="The Fellowship of the Ring",
        subtitle="The Lord of the Rings, Book One",
        author="J. R. R. Tolkien",
        narrator="Andy Serkis",
        album="The Fellowship of the Ring",
        year="2021",
        series="The Lord of the Rings",
        series_index="1",
    ),
    single(
        "The_Lord_of_the_Rings_J_R_R_Tolkien",
        "The Two Towers Lord of the Rings, Book 2.m4b",
        title="The Two Towers",
        subtitle="The Lord of the Rings, Book Two",
        author="J. R. R. Tolkien",
        narrator="Andy Serkis",
        album="The Two Towers",
        year="2021",
        series="The Lord of the Rings",
        series_index="2",
    ),
    single(
        "The_Lord_of_the_Rings_J_R_R_Tolkien",
        "The Return of the King Lord of the Rings, Book 3.m4b",
        title="The Return of the King",
        subtitle="The Lord of the Rings, Book Three",
        author="J. R. R. Tolkien",
        narrator="Andy Serkis",
        album="The Return of the King",
        year="2021",
        series="The Lord of the Rings",
        series_index="3",
    ),
    single(
        ".",
        "Blood Meridian_ Or the Evening Redness in the West (Unabridged).m4b",
        title="Blood Meridian",
        subtitle="Or the Evening Redness in the West",
        author="Cormac McCarthy",
        narrator="Richard Poe",
        album="Blood Meridian",
        year="2007",
        series="",
        series_index="",
    ),
    {
        "name": "Lincoln in the Bardo",
        "layout": "chapters",
        "glob": "George Saunders - Lincoln in the Bardo/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "",
            "author": "George Saunders",
            "narrator": LINCOLN_CAST,
            "album": "Lincoln in the Bardo",
            "genre": GENRE,
            "year": "2017",
            "series": "",
            "series_index": "",
            "description": None,
        },
    },
    {
        "name": "Best Served Cold",
        "layout": "chapters",
        "glob": "The First Law Standalones/The First Law 04 Best Served Cold/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "A First Law Novel",
            "author": ABERCROMBIE,
            "narrator": PACEY,
            "album": "Best Served Cold",
            "genre": GENRE,
            "year": "2016",
            "series": "The First Law",
            "series_index": "4",
            "description": DESC["best_served_cold"],
        },
    },
    {
        "name": "The Heroes",
        "layout": "chapters",
        "glob": "The First Law Standalones/The First Law 05 The Heroes/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "A First Law Novel",
            "author": ABERCROMBIE,
            "narrator": PACEY,
            "album": "The Heroes",
            "genre": GENRE,
            "year": "2011",
            "series": "The First Law",
            "series_index": "5",
            "description": DESC["the_heroes"],
        },
    },
    {
        "name": "Red Country",
        "layout": "chapters",
        "glob": "The First Law Standalones/The First Law 06 Red Country/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "A First Law Novel",
            "author": ABERCROMBIE,
            "narrator": PACEY,
            "album": "Red Country",
            "genre": GENRE,
            "year": "2012",
            "series": "The First Law",
            "series_index": "6",
            "description": DESC["red_country"],
        },
    },
    {
        "name": "Sharp Ends",
        "layout": "chapters",
        "glob": "The First Law Standalones/The First Law 07 Sharp Ends/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "Stories from the World of the First Law",
            "author": ABERCROMBIE,
            "narrator": PACEY,
            "album": "Sharp Ends",
            "genre": GENRE,
            "year": "2016",
            "series": "The First Law",
            "series_index": "7",
            "description": DESC["sharp_ends"],
        },
    },
    {
        "name": "World War Z: The Complete Edition",
        "layout": "parts",
        "glob": "World War Z m4b/*.m4b",
        "tags": {
            "title": "World War Z: The Complete Edition",
            "subtitle": "An Oral History of the Zombie War",
            "author": "Max Brooks",
            "narrator": "Full Cast",
            "album": "World War Z: The Complete Edition",
            "genre": GENRE,
            "year": "2013",
            "series": "",
            "series_index": "",
            "description": DESC["world_war_z"],
        },
    },
    {
        "name": "Just Kids",
        "layout": "discs",
        "disc_root": "Just Kids",
        "tags": {
            "title": "Just Kids",
            "subtitle": "",
            "author": "Patti Smith",
            "narrator": "Patti Smith",
            "album": "Just Kids",
            "genre": GENRE,
            "year": "2011",
            "series": "",
            "series_index": "",
            "description": DESC["just_kids"],
        },
    },
    single(
        "./Unfiltered",
        "The Witcher - The Last Wish.m4b",
        title="The Last Wish",
        subtitle="Introducing the Witcher",
        author="Andrzej Sapkowski",
        narrator="Peter Kenny",
        album="The Last Wish",
        year="2015",
        series="",
        series_index="",
        description=DESC["witcher_last_wish"],
    ),
    {
        "name": "Kitchen Confidential",
        "layout": "chapters",
        "glob": "Unfiltered/Anthony Bourdain - Kitchen Confidential - mp3/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "Adventures in the Culinary Underbelly",
            "author": "Anthony Bourdain",
            "narrator": "Anthony Bourdain",
            "album": "Kitchen Confidential",
            "genre": GENRE,
            "year": "2005",
            "series": "",
            "series_index": "",
            "description": DESC["bourdain_kc"],
        },
    },
    single(
        "./Unfiltered",
        "Christopher Buehlman - The Lesser Dead.m4b",
        title="The Lesser Dead",
        subtitle="",
        author="Christopher Buehlman",
        narrator="Christopher Buehlman",
        album="The Lesser Dead",
        year="2014",
        series="",
        series_index="",
        description=DESC["the_lesser_dead"],
    ),
    {
        "name": "The Road",
        "layout": "chapters",
        "glob": "Unfiltered/The Road -Cormac McCarthy/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "",
            "author": "Cormac McCarthy",
            "narrator": "Tom Stechschulte",
            "album": "The Road",
            "genre": GENRE,
            "year": "2007",
            "series": "",
            "series_index": "",
            "description": None,
        },
    },
    {
        "name": "Hyperion (Various Full Cast)",
        "layout": "chapters",
        "glob": "Unfiltered/The Hyperion Cantos - Dan Simmons/1989 - Hyperion (Various) 571mb/*.mp3",
        "tags": {
            "title": "Hyperion",
            "subtitle": "Hyperion Cantos, Book One (Full Cast narration)",
            "author": "Dan Simmons",
            "narrator": "Marc Vietor, Allyson Johnson, Kevin Pariseau, Jay Snyder & Victor Bevine",
            "album": "Hyperion (Various Full Cast)",
            "genre": GENRE,
            "year": "1989",
            "series": "Hyperion Cantos",
            "series_index": "1",
            "description": DESC["hyperion"],
        },
    },
    {
        "name": "The Fall of Hyperion (Bevine)",
        "layout": "chapters",
        "glob": "Unfiltered/The Hyperion Cantos - Dan Simmons/1990 - The Fall of Hyperion (Bevine) 600mb/*.mp3",
        "tags": {
            "title": "The Fall of Hyperion",
            "subtitle": "Hyperion Cantos, Book Two (Victor Bevine narration)",
            "author": "Dan Simmons",
            "narrator": "Victor Bevine",
            "album": "The Fall of Hyperion (Bevine)",
            "genre": GENRE,
            "year": "1990",
            "series": "Hyperion Cantos",
            "series_index": "2",
            "description": DESC["fall_hyperion"],
        },
    },
    {
        "name": "We Are Legion (We Are Bob)",
        "layout": "chapters",
        "glob": "Unfiltered/Dennis E. Taylor/Bobiverse/1 - We are Legion (We are Bob)/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "Bobiverse, Book One",
            "author": "Dennis E. Taylor",
            "narrator": "Ray Porter",
            "album": "We Are Legion (We Are Bob)",
            "genre": GENRE,
            "year": "2016",
            "series": "Bobiverse",
            "series_index": "1",
            "description": DESC["bobi1"],
        },
    },
    {
        "name": "The Black Company",
        "layout": "chapters",
        "glob": "Unfiltered/Glen Cook - Black Company Compilation/01 The Books of the North/01 The Black Company/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "Books of the North, Book One",
            "author": "Glen Cook",
            "narrator": "Marc Vietor",
            "album": "The Black Company",
            "genre": GENRE,
            "year": "1984",
            "series": "Books of the North",
            "series_index": "1",
            "description": DESC["bc1"],
        },
    },
    single(
        "Unfiltered/James S. A. Corey - The Expanse Complete 2.0 - Jefferson Mays",
        "The Expanse 1.0 - Leviathan Wakes (2011).m4b",
        title="Leviathan Wakes",
        subtitle="The Expanse, Book One",
        author="James S. A. Corey",
        narrator="Jefferson Mays",
        album="Leviathan Wakes",
        year="2011",
        series="The Expanse",
        series_index="01",
        description=DESC["exp_leviathan_wakes"],
    ),
    single(
        "Unfiltered/James S. A. Corey - The Expanse Complete 2.0 - Jefferson Mays",
        "The Expanse 2.0 - Caliban’s War (2012).m4b",
        title="Caliban’s War",
        subtitle="The Expanse, Book Two",
        author="James S. A. Corey",
        narrator="Jefferson Mays",
        album="Caliban’s War",
        year="2012",
        series="The Expanse",
        series_index="02",
        description=DESC["exp_calibans_war"],
    ),
    single(
        "./Unfiltered",
        "Lonesome Dove - Larry McMurtry, Taylor Sheridan - foreword.m4a",
        title="Lonesome Dove",
        subtitle="",
        author="Larry McMurtry",
        narrator="Will Patton",
        album="Lonesome Dove",
        year="2025",
        series="",
        series_index="",
    ),
    single(
        "Unfiltered/The Acts of Caine (Matthew Woodring Stover)",
        "01 Heroes Die.m4b",
        title="Heroes Die",
        subtitle="Acts of Caine, Book One",
        author="Matthew Stover",
        narrator="Stefan Rudnicki",
        album="Heroes Die",
        year="2011",
        series="Acts of Caine",
        series_index="1",
        description=DESC["caine1"],
    ),
    {
        "name": "The Master and Margarita",
        "layout": "chapters",
        "glob": "Unfiltered/Mikhail Bulgakov - The Master and Margarita - mp3/Mikhail Bulgakov - The Master and Margarita/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "",
            "author": "Mikhail Bulgakov",
            "narrator": "Julian Rhind-Tutt",
            "album": "The Master and Margarita",
            "genre": GENRE,
            "year": "2009",
            "series": "",
            "series_index": "",
            "description": DESC["master_margarita"],
        },
    },
    {
        "name": "Snow Crash",
        "layout": "parts",
        "glob": "Unfiltered/Neal Stephenson - Snow Crash/*.m4b",
        "tags": {
            "title": "Snow Crash",
            "subtitle": "",
            "author": "Neal Stephenson",
            "narrator": "Jonathan Davis",
            "album": "Snow Crash",
            "genre": GENRE,
            "year": "2001",
            "series": "",
            "series_index": "",
            "description": DESC["snow_crash"],
        },
    },
    single(
        "Unfiltered/Gentlemen Bastards/01 The Lies of Locke Lamora [B004K4EMHE]",
        "The Lies of Locke Lamora [B004K4EMHE].m4b",
        title="The Lies of Locke Lamora",
        subtitle="Gentleman Bastard, Book One",
        author="Scott Lynch",
        narrator="Michael Page",
        album="The Lies of Locke Lamora",
        year="2010",
        series="Gentleman Bastard",
        series_index="1",
        description=DESC["gentlemen_1"],
    ),
    single(
        "Unfiltered/Gentlemen Bastards/02 Red Seas Under Red Skies [B004K3OJ0K]",
        "Red Seas Under Red Skies [B004K3OJ0K].m4b",
        title="Red Seas Under Red Skies",
        subtitle="Gentleman Bastard, Book Two",
        author="Scott Lynch",
        narrator="Michael Page",
        album="Red Seas Under Red Skies",
        year="2010",
        series="Gentleman Bastard",
        series_index="2",
        description=DESC["gentlemen_2"],
    ),
    {
        "name": "The Gunslinger",
        "layout": "chapters",
        "glob": "Unfiltered/Stephen King - The Dark Tower 1 - 4/Stephen King - D T 01 The Gunslinger/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "The Dark Tower, Book One",
            "author": "Stephen King",
            "narrator": "Frank Muller",
            "album": "The Gunslinger",
            "genre": GENRE,
            "year": "1997",
            "series": "The Dark Tower",
            "series_index": "1",
            "description": DESC["dt1"],
        },
    },
    {
        "name": "The Drawing of the Three",
        "layout": "chapters",
        "glob": "Unfiltered/Stephen King - The Dark Tower 1 - 4/Stephen King - D T 02 The Drawing Of The Three/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "The Dark Tower, Book Two",
            "author": "Stephen King",
            "narrator": "Frank Muller",
            "album": "The Drawing of the Three",
            "genre": GENRE,
            "year": "1997",
            "series": "The Dark Tower",
            "series_index": "2",
            "description": DESC["dt2"],
        },
    },
    {
        "name": "The Waste Lands",
        "layout": "chapters",
        "glob": "Unfiltered/Stephen King - The Dark Tower 1 - 4/Stephen King - D T 03 The Wastelands/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "The Dark Tower, Book Three",
            "author": "Stephen King",
            "narrator": "Frank Muller",
            "album": "The Waste Lands",
            "genre": GENRE,
            "year": "1997",
            "series": "The Dark Tower",
            "series_index": "3",
            "description": DESC["dt3"],
        },
    },
    {
        "name": "Wizard and Glass",
        "layout": "chapters",
        "glob": "Unfiltered/Stephen King - The Dark Tower 1 - 4/Stephen King - D T 04 Wizard and Glass/*.mp3",
        "tags": {
            "title": None,
            "subtitle": "The Dark Tower, Book Four",
            "author": "Stephen King",
            "narrator": "Frank Muller",
            "album": "Wizard and Glass",
            "genre": GENRE,
            "year": "1997",
            "series": "The Dark Tower",
            "series_index": "4",
            "description": DESC["dt4"],
        },
    },
    single(
        "./Unfiltered",
        "Piranesi by Susanna Clarke.m4b",
        title="Piranesi",
        subtitle="",
        author="Susanna Clarke",
        narrator="Chiwetel Ejiofor",
        album="Piranesi",
        year="2020",
        series="",
        series_index="",
    ),
    single(
        "Unfiltered/Tamsyn Muir - Gideon the Ninth The Locked Tomb Trilogy, Book 1",
        "Gideon the Ninth The Locked Tomb Trilogy, Book 1.m4b",
        title="Gideon the Ninth",
        subtitle="The Locked Tomb, Book One",
        author="Tamsyn Muir",
        narrator="Moira Quirk",
        album="Gideon the Ninth",
        year="2019",
        series="",
        series_index="",
    ),
    {
        "name": "Lolita",
        "layout": "parts",
        "glob": "Unfiltered/Lolita/*.mp3",
        "tags": {
            "title": "Lolita",
            "subtitle": "",
            "author": "Vladimir Nabokov",
            "narrator": "Jeremy Irons",
            "album": "Lolita",
            "genre": GENRE,
            "year": "1997",
            "series": "",
            "series_index": "",
            "description": DESC["lolita"],
        },
    },
    # ---- Pierce Brown / Red Rising (Audible Studios / Recorded Books) --------
    single(
        "Unfiltered/Red Rising Series Audible",
        "Red Rising by Pierce Brown Book 1.m4b",
        title="Red Rising",
        subtitle="Red Rising Saga, Book One",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds",
        album="Red Rising",
        year="2014",
        series="Red Rising",
        series_index="1",
        description=DESC["red_rising"],
    ),
    single(
        "Unfiltered/Red Rising Series Audible",
        "Golden Son by Pierce Brown Book 2.m4b",
        title="Golden Son",
        subtitle="Red Rising Saga, Book Two",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds",
        album="Golden Son",
        year="2015",
        series="Red Rising",
        series_index="2",
        description=DESC["golden_son"],
    ),
    single(
        "Unfiltered/Red Rising Series Audible",
        "Morning Star by Pierce Brown Book 3.m4b",
        title="Morning Star",
        subtitle="Red Rising Saga, Book Three",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds",
        album="Morning Star",
        year="2016",
        series="Red Rising",
        series_index="3",
        description=DESC["morning_star"],
    ),
    single(
        "Unfiltered/Red Rising Series Audible",
        "Iron Gold by Pierce Brown Book 4.m4b",
        title="Iron Gold",
        subtitle="Red Rising Saga, Book Four",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds, John Curless, Julian Elfer & Aedin Moloney",
        album="Iron Gold",
        year="2018",
        series="Red Rising",
        series_index="4",
        description=DESC["iron_gold"],
    ),
    single(
        "Unfiltered/Red Rising Series Audible",
        "Dark Age by Pierce Brown Book 5.m4b",
        title="Dark Age",
        subtitle="Red Rising Saga, Book Five",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds, John Curless, Moira Quirk, James Langton & Rendah Heywood",
        album="Dark Age",
        year="2019",
        series="Red Rising",
        series_index="5",
        description=DESC["dark_age"],
    ),
    single(
        "Unfiltered/Red Rising Series Audible",
        "Light Bringer By Pierce Brown Book 6.m4b",
        title="Light Bringer",
        subtitle="Red Rising Saga, Book Six",
        author="Pierce Brown",
        narrator="Tim Gerard Reynolds",
        album="Light Bringer",
        year="2023",
        series="Red Rising",
        series_index="6",
        description=DESC["light_bringer"],
    ),
]
